spring: 
  jpa: 
    show-sql: true
    hibernate:
      ddl-auto: create-drop  
  datasource: 
    primary:  
      jdbc-url: jdbc:mysql://121.43.162.28:3306/primary
      username: root
      password: passw0rd
      driver-class-name:  com.mysql.jdbc.Driver
    secondary:  
      jdbc-url: jdbc:mysql://121.43.162.28:3306/secondary
      username: root
      password: passw0rd
      driver-class-name:  com.mysql.jdbc.Driver     