spring: 
  redis:  
    timeout:  0
    database: 0
    host: 121.43.162.28
    port: 6379
    password: passw0rd
    jedis:  
      pool:  
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0